### ISSUE TITLE
Таймаут в HC_SR04_read 

### ISSUE THREAD

**Issue by 14droplets** [m-in-the-power-of-3/cansat-2016#2]
проблема в функции `HC_SR04_read`, а конкретно в ожиданиях появления сигнала "эхо".

Вызывает легкое беспокойство строка `while ((US_PPIN & (1 << US_pin_ECHO)) == 0){}` вот [тут](https://github.com/m-in-the-power-of-3/cansat-2016/blob/master/M_3_board/main_folder/HC_SR04.c#L30)

Если в полете что-то пойдет не так и датчик отвалится - сигнал может не прийти никогда, что поставит микроконтроллер в бесконечный цикл

**Comment by Agnus290** [comment]
Я же вроде его уже сделала?

**Comment by 14droplets** [comment]
Ну тогда надо закрыть ишью
